name: app
type: php:7.0
build:
  flavor: composer
disk: 2048

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.html
      allow: true

relationships:
  database: "mysqldb:mysql"
  
# mounts:
#   "test-mount": "shared:files/test-mount"
  
# hooks:
#   build: |
#     echo "This is the build hook firing!"
#   deploy: |
#     echo "This is the deploy hook firing!"