http://www.{default}/:
  cache:
    cookies: []
    default_ttl: 600
    enabled: true
    headers:
    - User-Agent
    - user-agent
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: false
  type: upstream
  upstream: app:http
http://{default}/:
  to: http://www.{default}/
  type: redirect
